[server]
port = ":8080"

[mysql]
enabled = true
type = "mysql"
host = "mysql"   # docker-compose service name
#host = "127.0.0.1" # local
port = 3306
#port = 3308 # local
user = "root"
password = "123456"
dbname = "fliqt"
max_idle_conn = 10
max_open_conn = 100

[gorm]
debug = true

[redis]
addr = "redis:6379"
#addr = "localhost:6380" # local
password = ""
db = 0
