[server]
port = ":8080"

[mysql]
enabled = true
type = "mysql"
host = "127.0.0.1"
port = 3308
user = "root"
password = "123456"
dbname = "fliqt"
max_idle_conn = 10
max_open_conn = 100

[gorm]
debug = true

[redis]
addr = "localhost:6380"
password = ""
db = 0
