// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"FliQt/internals/app/api"
	"FliQt/internals/app/config"
	"FliQt/internals/app/repository"
	"FliQt/internals/app/router"
	"FliQt/internals/app/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func injector(cfg *config.Config) (*Application, func(), error) {
	iLeaveRepository := repository.NewLeaveRepository()
	repo := &repository.Repo{
		LeaveRepository: iLeaveRepository,
	}
	iLeaveService := service.NewLeaveService(repo)
	srv := &service.Srv{
		LeaveService: iLeaveService,
	}
	iLeaveAPI := api.NewLeaveAPI(srv)
	engine := router.New(cfg, iLeaveAPI)
	application := &Application{
		Engine: engine,
	}
	return application, func() {
	}, nil
}

// wire.go:

type Application struct {
	Engine *gin.Engine
}

func Start(cfg *config.Config) (*Application, func(), error) {
	return injector(cfg)
}
